name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          depth: 0 # <- Suggested to get all tags
          token: ${{ secrets.GH_TOKEN }} # <- This is required

      - name: Release
        uses: mbround18/auto@v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
